// <auto-generated />
using System;
using CountryPackage.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountryPackage.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827123603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("CountryPackage.Api.Domain.ApprovalStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CountryPackageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DistributedDocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DraftDocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipientUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredClearance")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewDecision")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SnapshotDocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistributedDocumentVersionId");

                    b.HasIndex("DraftDocumentVersionId");

                    b.HasIndex("SnapshotDocumentVersionId");

                    b.HasIndex("CountryPackageId", "Order")
                        .IsUnique();

                    b.HasIndex("ReviewerUserId", "Status");

                    b.ToTable("ApprovalSteps", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApprovalSteps_Order", "\"Order\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.AuditEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryPackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafeDetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryPackageId", "StepOrder", "OccurredAt");

                    b.ToTable("AuditEntries", (string)null);
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.CountryPackageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("CountryPackages", (string)null);
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.DocumentVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryPackageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryPackageId", "UploadedAt");

                    b.ToTable("DocumentVersions", (string)null);
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.EvidenceManifestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationFindingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentVersionId")
                        .IsUnique();

                    b.ToTable("EvidenceManifests", (string)null);
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.IdempotencyRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CountryPackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryPackageId");

                    b.HasIndex("ActorUserId", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.ApprovalStepEntity", b =>
                {
                    b.HasOne("CountryPackage.Api.Domain.CountryPackageEntity", "CountryPackage")
                        .WithMany("Steps")
                        .HasForeignKey("CountryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CountryPackage.Api.Domain.DocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("DistributedDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CountryPackage.Api.Domain.DocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("DraftDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CountryPackage.Api.Domain.DocumentVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("SnapshotDocumentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CountryPackage");
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.AuditEntryEntity", b =>
                {
                    b.HasOne("CountryPackage.Api.Domain.CountryPackageEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.DocumentVersionEntity", b =>
                {
                    b.HasOne("CountryPackage.Api.Domain.CountryPackageEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.EvidenceManifestEntity", b =>
                {
                    b.HasOne("CountryPackage.Api.Domain.DocumentVersionEntity", "DocumentVersion")
                        .WithOne("EvidenceManifest")
                        .HasForeignKey("CountryPackage.Api.Domain.EvidenceManifestEntity", "DocumentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentVersion");
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.IdempotencyRecordEntity", b =>
                {
                    b.HasOne("CountryPackage.Api.Domain.CountryPackageEntity", null)
                        .WithMany()
                        .HasForeignKey("CountryPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.CountryPackageEntity", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CountryPackage.Api.Domain.DocumentVersionEntity", b =>
                {
                    b.Navigation("EvidenceManifest");
                });
#pragma warning restore 612, 618
        }
    }
}
